### ISSUE TITLE
Interacción con Canvas

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carpineti-castellani#12]
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/assets/8345007/a6f32522-c6e1-4462-acb6-a900390052e3)
* Es muy complicado hacer un diseño si el usuario no puede "arrastrar" el mouse. El mouse se debería poder mover similar al ejercicio de mini-paint.
* La superficie del canvas para realizar el diseño es pequeña
* Además del color, el usuario debería poder seleccionar el grosor de la línea

**Comment by francocaste2705** [comment]
Errores del Canva solucionados.
