### ISSUE TITLE
Se deben documentar de manera adecuada todas las funciones Js

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carpineti-castellani#15]
https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e9b2de69a61ee28eb83327e769a692fba26261da/scripts/canva.js#L16

https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e9b2de69a61ee28eb83327e769a692fba26261da/scripts/canva.js#L22

https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e9b2de69a61ee28eb83327e769a692fba26261da/scripts/form.js#L68

La forma de documentación es:
```
/**
 * Descripción de que hace la función
 * @method Nombre de la función
 * @param {string} ParámetroA - Explicación de que valor almacena ParámetroA
 * @param {number} ParámetroB - Explicación de que valor almacena ParámetroB
 * @return Valor que retorna
 */
```

**Comment by francocaste2705** [comment]
Corregido
