### ISSUE TITLE
Sugerencia: Corregir los errores de ortografía

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carpineti-castellani#4]
Agregar tildes en las palabras que correspondan:
* Título
* Descripción
* página
* Tecnologías

![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/assets/8345007/001374f9-170d-40f8-9e65-f05f15df9895)

**Comment by edme88** [comment]
Faltan algunas tildes:
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/assets/8345007/13df9387-ab91-4e13-a874-9da24c50d590)

**Comment by edme88** [comment]
Aún falta la tilde en además
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/assets/8345007/a44ad69f-5e5b-4336-838f-0226f6fbc392)

**Comment by francocaste2705** [comment]
Errores corregidos
