### ISSUE TITLE
Las imágenes deben ser incluidas en el repositorio

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carpineti-castellani#7]
Las imágenes deben ser incluidas en el repositorio, porque si la url externa llegase a desaparecer, se quedarían sin el recurso imagen.

https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e254a716a4f05529422790a0eefc93386e82a350/pages/login.html#L26

https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e254a716a4f05529422790a0eefc93386e82a350/pages/main.html#L44-L47

https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e254a716a4f05529422790a0eefc93386e82a350/pages/main.html#L53-L56

https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e254a716a4f05529422790a0eefc93386e82a350/pages/main.html#L72-L76

https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e254a716a4f05529422790a0eefc93386e82a350/pages/main.html#L81-L84

https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e254a716a4f05529422790a0eefc93386e82a350/pages/main.html#L90-93

**Comment by edme88** [comment]
Las imágenes deben ser incluidas en el repositorio, porque si la url externa llegase a desaparecer, se quedarían sin el recurso imagen.
https://github.com/UCC-LabCompu2/proyecto2023-carpineti-castellani/blob/e9b2de69a61ee28eb83327e769a692fba26261da/pages/login.html#L30

**Comment by edme88** [comment]
Aún falta corregir este detalle.

**Comment by francocaste2705** [comment]
Corregido
